### ISSUE TITLE
Add fake for unit testing of library user

### ISSUE THREAD

**Issue by tweksteen** [godbus/dbus#157]
With #26, it is already somewhat possible to mock the library for unit testing. However, there is a lot of boilerplate code to reproduce a functional dbus environment. [Barista](https://github.com/soumya92/barista) includes a [generic fake for dbus](https://github.com/soumya92/barista/blob/master/base/watchers/dbus/testbus.go). Would you be open to somehow include this fake here so that consumer of dbus can easily unit test their library?

**Comment by amenzhinsky** [comment]
If you have dbus package installed on your system you can use `dbus-launch --exit-with-session go test ./...` to start unit tests that provides an isolated session bus. Or even start the daemon manually it the test suite with `dbus-daemon --session --print-address`. 

I don't think that maintaining a mock is going to pay out because that equals implementing fully working daemon that complies with the dbus specification and there's always some place to make a mistake.

**Comment by tweksteen** [comment]
That make sense. I agree. Thanks!
