### ISSUE TITLE
Feature request: expose received message byte order

### ISSUE THREAD

**Issue by dshynkev** [godbus/dbus#210]
This is not a complicated code change, but I wanted to put the proposal up for discussion first.

## Proposal

Add a `ByteOrder binary.ByteOrder` field to `Message`. When receiving, it is set to the (presently unexposed) byte order inferred from the first byte of the message. When sending, it defaults to `nativeEndian` if set to `nil`, else is used directly. In the next major release, the `order` parameter can be retired from `EncodeTo`, given that the `Message` struct would now carries that information.

## Motivation

Unfortunately, certain services have designed their DBus APIs in a way that requires the client to know the byte order of the host the service is running on.

For example, some structures used by NetworkManager (such as the [`ipv4` settings object](https://developer.gnome.org/NetworkManager/stable/settings-ipv4.html)) encode IPv4 addresses as `uint32`s in what is documented to be "network byte order". As far as I can tell, this is not even correct, and [comment 4 here](https://bugzilla.redhat.com/show_bug.cgi?id=1153559#c4) is right: to attain the right outcome when trying to transmit the address `8.8.4.4`, I find myself having to send `0x04040808` on `amd64` and `0x08080404` on `mips`, which suggests host byte order. But even if this were not the case, the other comments on the same bug agree that the client needs to know the byte order of the host NetworkManager is running on in case that host is a remote one and differs in byte order.

**Comment by jhenstridge** [comment]
For the NetworkManager case, it is almost certainly saying it wants the result of integers converted via the libc `htonl`/`ntohl` functions.  That's likely going to be true no matter which way endian D-Bus message is encoded, since the daemon will be dealing with the data in the decoded message.

What you really want here is a "perform a byte swap if the CPU is lttle endian" function.  You could either use the existing libc functions via cgo, or code up something equivalent in Go.

**Comment by guelfey** [comment]
This is not something that's in scope of this library. It transparently handles the byte order of the marshaled message, which actually could be big or little endian completely independent of what the endianness of the local system is (since D-Bus also theoretically supports networking), so exposing this info wouldn't even be useful in this case. The message endianness is purely for transport purposes and should not have an influence on how the data is interpreted. So this is sadly just a bad API on NetworkManager's part. You can still detect the host endianness in the application code; for what it's worth, the linked page also states that `addresses` is deprecated in favor of `address-data` where the address is stored as a string.
