### ISSUE TITLE
After connection Close() called, SystemBus() check systemBus != nil, which cause next Store() return error: 'dbus: connection closed by user' !

### ISSUE THREAD

**Issue by zzcontinent** [godbus/dbus#222]
1. I called godbus API like:
for {
conn,err := dbus.SystemBus()
defer conn.Close()
err := conn.Object().Call(...).Store(...)
}
--> err 'dbus: connection closed by user' 
I found out that SystemBus()  check systemBus != nil. 

2. At last , I have to change my code from dbus.SystemBus() to  
conn, err = dbus.SystemBusPrivate()
if err != nil {
	return err
}
if err = conn.Auth(nil); err != nil {
	conn.Close()
	return err
}
if err = conn.Hello(); err != nil {
	conn.Close()
	return err
}

3. Should systemBus be set to nil when Close() called?

**Comment by jhenstridge** [comment]
Closing a D-Bus connection you do not own (such as the shared session and system connections) is a logic error in your program.  Think of this as similar to the error of closing a channel that other goroutines might try to write to.

I agree that it would be good to flag an error like this, but that might be in the form of making Close() fail (panic?) on such a call.

With that said, I agree that there are many cases where you want to be able to control when a connection is closed, since it is the best way to clean up some state.  The fact that `SystemBusPrivate` does not return a connection that is ready to use is a wart in the godbus API.  I kind of wonder if anyone takes advantage of not authenticating or calling Hello on a new connection?
