### ISSUE TITLE
DBus activation doesn't work for initial method call

### ISSUE THREAD

**Issue by kyrofa** [godbus/dbus#23]
DBus activation has the following event flow:

1. Process A makes a DBus method call with DBus name "com.example.Foo" and method "com.example.Interface.MethodName."
2. DBus notices that there is no process on the bus with the name "com.example.Foo."
3. DBus launcher looks through /usr/share/dbus-1/services (for session bus services) for a .service file for a DBus service with the name "com.example.Foo." If it doesn't find one, it returns a "No such service" error and breaks this flow.
4. If it does find one, it launches the process with the information from the .service file.
5. It waits until the process has been granted the name "com.example.Foo" (i.e the NameAcquired signal).
6. It sends the method call to the process.

The problem for godbus is the time between steps 5 and 6. Since the name request (and corresponding NameAcquired signal) are handled asynchronously, and the method call is also handled asynchronously, and the time between steps 5 and 6 is minuscule, it's possible (indeed, it happens every time for me) for the NameAcquired signal to be emitted but not completely handled before the method call comes in as well. This results in the method call being discarded since godbus hasn't saved the fact that the name has been acquired, so godbus thinks the message came in via an eavesdrop with no corresponding channel.

This results in the initial method call (which caused the activation) to receive no reply. Subsequent method calls work fine since the NameAcquired signal has since been handled.

There needs to be some way of synchronously acquiring the name (or at least synchronously handling that signal before handling another message), or godbus simply can't be used for DBus activation.

**Comment by kyle-f** [comment]
Please note that I'd be happy to contribute the fix for this, but it potentially requires a redesign of the name handling in godbus, and I'm not sure I'm the most qualified to do that. My first take on this is that `NameAcquired` should be handled the same way `NameLost` is handled-- right within `inWorker()`.

**Comment by philips** [comment]
This sounds like something we should fix so a patch would be accepted. I don't know that code path well enough to evaluate your approach at this moment though.

**Comment by kyle-f** [comment]
Okay, I'm taking a crack at it now. Then you can review the MR and evaluate the approach :smiley: .

**Comment by kyle-f** [comment]
Alright, after some more investigation, I have some more information. This information was obtained via looking at the dbus source code (version 1.8.12). This is not a sometimes-occurring race condition but a (very slight) misunderstanding of DBus that will _always_ happen when using godbus with DBus activation. Let's break down steps 5 and 6 from the bug report further into the actual steps that happen as per the dbus source code:

1. Process calls RequestName
2. dbus grants name request, emits NameAcquired
3. godbus receives NameAcquired signal and passes it along via the signals channel
4. dbus calls queued method calls now that name has been acquired
5. godbus receives the method call, and drops it on the floor since it doesn't know it has that name
6. dbus provides reply for RequestName call
7. godbus receives reply, and now knows it has that name
8. Subsequent method calls work fine since it's now correctly tracking the name

So the fix is pretty much the same as I suggested, but now it has a solid reason: Self-name-tracking should be done via the dbus NameAcquired/NameLost signals rather than the method calls, or name tracking will not always reflect the correct dbus state. `RequestName()` and `ReleaseName()` are to be used only for tracking whether the name was successfully acquired/released, not for tracking one's names. This is actually quite a nice simplification-- now the only file that will touch the names is `conn.go`. I will make a MR that moves name tracking into inWorked() utilizing those two signals, and extract the name tracking from `RequestName()` and `ReleaseName()`.
