### ISSUE TITLE
Responses sequence must be ordered by incoming message serial

### ISSUE THREAD

**Issue by slytomcat** [godbus/dbus#327]
[Here](https://github.com/fyne-io/systray/issues/12) is the core problem: when responses are sent without right order (first-in-first-out) from interface com.canonical.dbusmenu sub-menus are not shown in XFCE environment.

The simplest patch: is to remove `go` keyword from 
https://github.com/godbus/dbus/blob/16fef229d18992a4f4143df7f8e55320f891e32b/conn.go#L434

**Comment by guelfey** [comment]
I'm inclined to interpret this as a bug in XFCE. If I understand your logs right, then it's sending the different GetGroupProperties calls in parallel. There's nothing in the D-Bus spec that mentions that method calls need to be handled in the same order that they arrive; if the caller depends on this, it should do the calls synchronously and wait for each reply. Maybe check in the source code of the component if this can be fixed easily, though if this is a core assumption of libdbus or gdbus, it might be harder to fix.

But I think you're right in that without a fix there, it's also not possible to work around from your application, since the ultimate order of the replies is out of your control. Making method call handling completely synchronous in all cases is also not great; the best solution I can come up with is an additional `ConnOption` that makes method call replies synchronous.

**Comment by slytomcat** [comment]
I also not sure that D-Bus calls need to be handled in the same order that they arrive as I see the problem only in XFCE environment. I tested my app in different distributions. There is no such issue in Ubuntu/Kubuntu/Lubuntu. It appears only in Xubuntu. 

So, I've opened the issue in the [gitlab.xfce.org/panel-plugins](https://gitlab.xfce.org/panel-plugins/xfce4-statusnotifier-plugin/-/issues/20).
