### ISSUE TITLE
Impossible to export to subtree

### ISSUE THREAD

**Issue by kyrofa** [godbus/dbus#34]
Currently in godbus, it's possible to register an object at a given object path, i.e. `Export(MyStruct{}, "/foo", "my.interface")`, and method calls coming in on that object path are dispatched to that struct.

However, although the dbus spec allows it, it's not possible to register an endpoint for an entire subtree of object paths. In the example above, method calls coming in on the object path `/foo/bar` will result in a "no such method" error.

There are a number of use-cases for this. In our case, we need to register for an entire subtree in order to take advantage of AppArmor's DBus integration, which means we'd like to see this feature in godbus.

I'm happy to write this feature, but I want to get the OK before beginning.

Keeping in mind the following goals:

1) Need to be able to register for an entire subtree of object paths
2) Need to know which object path was used for the method call
3) Need to know the sender of the message

I propose one of the following ideas:

Method 1
=======

Modify `Export` functions to support a wildcard in the object path, e.g. `Export(MyStruct{}, "/foo/*", "my.interface")`. The presence of the wildcard indicates a desire to be called for the entire `/foo/` subtree (e.g. `/foo/bar`, `/foo/baz`, etc.), and the method dispatching can do method lookups accordingly. This will satisfy (1) above.

(2) and (3) can be satisfied by changing the API of exported methods in `MyStruct{}` to require that the first parameter accepts a dbus.Message, which allows for access to the lower-level detailed required, e.g.:

```go
type MyStruct struct{}

func (m MyStruct) foo(message dbus.Message, param1, param2 string) (string, *dbus.Error) {
        return "hello world"
}
```

Using some reflection tricks it may be possible to make that first parameter optional thus not breaking API, but that might make things less obvious.

Summary
--------------

Advantages:
   - Easier to write
   - Easier to maintain
   - Intuitive to use

Disadvantages:
   - Probably breaks API
   - Potentially dilutes the clarity of `Export` usage since it can be used multiple ways

Method 2
=======

Add new ExportSubtree functions that work the same way as the current Export functions, but registers the struct for the entire subtree instead of just that specific object path. For example, `ExportSubtree(MyStruct{}, "/foo", "my.interface")` would indicate a desire to be called for the entire `/foo` subtree (e.g. `/foo/bar`, `/foo/baz`, etc.), and the method dispatching can do method lookups accordingly. This will satisfy (1) above.

(2) and (3) can be satisfied by requiring that functions on structs exported via ExportSubtree accept a dbus.Message as their first parameter, which allows for access to the lower-level detailed required (same example as the one given in Method 1).

Summary
-------------

Advantages:
   - Doesn't break API
   - Obviously works differently from the regular `Export` functions, so it's user-friendly and clear

Disadvantages:
   - More work to write
   - More work to maintain since two export code paths must be supported

I'm looking to start a discussion here and settle on a solution which I'm then happy to contribute. Thanks for your thoughts!

**Comment by dobey** [comment]
I think adding an `ExportSubtree()` method is a better solution, as it makes the API explicit. It should only be more work to write if there's a need to refactor any existing code, so that certain back-end implementation details can be shared across both APIs. I'd also suggest that for the ExportSubtree case, the methods are called with the dbus.Message and the dbus.ObjectPath, are the first two arguments, rather than only the Message. The ObjectPath is the most relevant item required for subtree implementations, and Message may only be needed for further advanced security checks or such. I don't think it should be significantly more work to maintain this, as most of the core implementation should be shared, and only pieces specific to the matching of subtree handling should be necessary to maintain separately from existing code.

**Comment by alexlarsson** [comment]
I think ExportSubtree() is the way to go. However, I also think that the proposed method is perhaps to simple. Compare for instance with the lowlevel similar call in gdbus: https://developer.gnome.org/gio/stable/GDBusConnection.html#g-dbus-connection-register-subtree

It allows you things like enumerating and introspecting the subtree as well as dynamically creating objects on demand. I think we should have similar abilities.

**Comment by kyrofa** [comment]
@alexlarsson I agree that those capabilities are necessary, but godbus doesn't have any of those features right now (e.g. dynamic introspection), and I feel like they're features that can use this as a building block rather than trying to do them all here. I suggest we get an `ExportSubtree()` function here that adds only the features necessary to export on a subtree, and then begin adding the other pieces that would affect the rest of godbus. Sound okay?

**Comment by dobey** [comment]
I've tried kyrofa's changes in a project where we need this feature, and it seems to work as we need. Accessing the path element of the message is slightly annoying, but that's something to be fixed in a separate issue/merge. The path is accessible, and we can rely on apparmor rules for restricting access based on the subtree path.

**Comment by kyrofa** [comment]
Thanks dobey! @alexlarsson @philips can you guys take a look at the associated PR #35?
