### ISSUE TITLE
Non-static property values

### ISSUE THREAD

**Issue by KentaKariya** [godbus/dbus#350]
I'm trying to implement a property which value is not static and must be evaluated dynamically for each call. Is there a way to update the value dynamically on read after exporting them & without making the property writable to clients?

**Comment by guelfey** [comment]
At least not using the `prop` subpackage, since it has the pretty much fixed assumption that it "owns" the actual value and keeps it inside of its internal map. But you're free to write your own implementation of `org.freedesktop.DBus.Properties` - you pretty much only need to implement `Get`, `GetAll` and `Set` like `prop.Properties` does:
```
func (p *Properties) Get(iface, property string) (dbus.Variant, *dbus.Error)
func (p *Properties) GetAll(iface string) (map[string]dbus.Variant, *dbus.Error)
func (p *Properties) Set(iface, property string, newv dbus.Variant) *dbus.Error
```
Then you can put whatever logic you want into the methods. See https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties for some more information on what clients might expect as behavior.
